[package]
name = "guessing_game"
version = "0.1.0"
edition = "2018"
authors = [" kcodin <35337381+kcodinkz@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.15"
